CREATE DATABASE IF NOT EXISTS @@KEYSTONE_DB@@;
GRANT ALL PRIVILEGES ON @@KEYSTONE_DB@@.* TO '@@KEYSTONE_DB_USER@@'@'localhost' IDENTIFIED BY '@@KEYSTONE_DB_PASSWD@@';
GRANT ALL PRIVILEGES ON @@KEYSTONE_DB@@.* TO '@@KEYSTONE_DB_USER@@'@'%' IDENTIFIED BY '@@KEYSTONE_DB_PASSWD@@';
FLUSH PRIVILEGES;

