CREATE DATABASE IF NOT EXISTS @@DB_NAME@@;
GRANT ALL PRIVILEGES ON @@DB_NAME@@.* TO '@@DB_USER@@'@'localhost' IDENTIFIED BY '@@DB_PASSWORD@@';
GRANT ALL PRIVILEGES ON @@DB_NAME@@.* TO '@@DB_USER@@'@'%' IDENTIFIED BY '@@DB_PASSWORD@@';
FLUSH PRIVILEGES;

